### ISSUE TITLE
Add A "Mascot"

### ISSUE THREAD

**Issue by Abby-Chang** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#12]
I think adding pictures/a "mascot" can make the calc look more fun/appealing, so it doesn't look _as_ bland/empty as it currently is.

Not sure how to do it _exactly_, but maybe a small 100x100-ish image with a small text box with the questions inside instead of just the text floating on flat background. Could just make a smaller rectangular text box with an image on the left (like in Undertale or something) with the question on the right. Or just flip the day choice thing horizontally, make it thinner, and add a square/divide a section to put the image into.

Or just slap the image onto the game and call it a day.

<img width="594" alt="heb" src="https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146913984/86c1f903-f143-4585-8d70-47494365b6fc">

**Comment by anipoli** [comment]
I can do this, and I also can try to make it animated with key framing

**Comment by anipoli** [comment]
Sketches:

![Mascot](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146810509/24a8ed1b-e897-4b2d-a1df-9394ea1b9e76)

**Comment by WilliamOpenshaw** [comment]
Please, anyone who wants to make a mascot, add your sketches to this issue as comments.
Once we have the mascots, we can work on preparing them for use in the program.
We don't have to have just one mascot.

**Comment by WilliamOpenshaw** [comment]
Is this a mascot you would like to use?
Or is it just an example?

![image](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/66886c28-5705-4b3e-8238-a03d8c2677b8)

**Comment by WilliamOpenshaw** [comment]
@Abby-Chang 
Please post your mascot here as soon as you have a rough sketch, thank you :)

**Comment by WilliamOpenshaw** [comment]
> Sketches:
> 
> ![Mascot](https://user-images.githubusercontent.com/146810509/272799867-24a8ed1b-e897-4b2d-a1df-9394ea1b9e76.png)

These mascots are great.
We can use your mascots and Abby's mascot.
Let me know in class when you would like to try animating it, and I'll show you how to animate it in unity in class or after class.

**Comment by CooperChenn** [comment]
It is finished
