### ISSUE TITLE
the shape of text

### ISSUE THREAD

**Issue by chi0729** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#14]
What is the change?
The corners of the text change into not that sharp.
Why do you want this change? 
I think if the corners are sharp are actually don't want to watch too long.
How can we make this change? 
I'm not really sure about it, but I guess we can change it in the text detail area.

**Comment by anipoli** [comment]
Added rounded corners:
<img width="1382" alt="Screenshot 2023-10-05 at 10 09 37 AM" src="https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146810509/f2839b14-feb8-4c4e-8856-dfe64f228db4">
<img width="1371" alt="Screenshot 2023-10-05 at 10 26 19 AM" src="https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146810509/1e39f8a9-5c11-4670-a0fa-6b27fa6427af">
<img width="1376" alt="Screenshot 2023-10-05 at 10 26 30 AM" src="https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146810509/81ad2a8d-7e67-4d42-a69a-9800cfbd3a7c">

**Comment by WilliamOpenshaw** [comment]
It has been done :)
