### ISSUE TITLE
I want the button of the page that choose the theory are not squared

### ISSUE THREAD

**Issue by AlstonKuo** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#15]
What is the change?
I want the button of the page that choose the theory are not fall squared, I don't want the angle of the squared be 90ﾟ, maybe change it to quite round.
Why do you want this change?
Because I think squared would not look good, maybe this change would made the people playing this game more comfortable.
How can me make this change?
I'm not sure how to do this. But I think there is a option of change the image of the game.

**Comment by anipoli** [comment]
#14 ?

**Comment by WilliamOpenshaw** [comment]
I will close this issue as Annie has found a solution for it, and changed the program.
Please add more information or re-open the issue if you feel more changes need to be made.
This is how it looks now:

![Screenshot 2023-10-06 095609](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/6a6f77bb-a3b1-4ab3-8381-ae696a2726e4)

![Screenshot 2023-10-06 095626](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/7c28f7ef-a88f-420f-9d75-a9feac7b788d)

![Screenshot 2023-10-06 095638](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/6200eb96-a5a0-4a24-8d1c-8b86eec517c1)

**Comment by WilliamOpenshaw** [comment]
Since it is changed for now, I will close the issue.
