### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by AlonzoChen** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#16]
I think we need to change the backround color, because the color is not mach, so we can change the color to porple.

**Comment by abcdefghijnajn28498y** [comment]
I'll change it, but did you mean all backgrounds?

**Comment by aesliea** [comment]
purple is good

**Comment by forestlin49** [comment]
I think purple is a good choice

**Comment by anipoli** [comment]
Maybe it could be white, maybe sightly off-white, since it gives a sense of purity.

**Comment by BaboBrendan** [comment]
i think purple is very good !!!

**Comment by Abby-Chang** [comment]
Maybe a gray-purple, like this?: 453f4d
Otherwise preferably not a violent, saturated purple. Lavender would be cool.

**Comment by chelseahu0129** [comment]
Or maybe a color like #8e829e?
This color is not that gray and not that dark so it won't catch people's attention.

**Comment by aesliea** [comment]
#b091cf

**Comment by abcdefghijnajn28498y** [comment]
#beabd1

**Comment by aesliea** [comment]
#cbbdde

**Comment by chi0729** [comment]
#afa1c7

**Comment by carlson04** [comment]
I agree. I'll try to make it purple

**Comment by WilliamOpenshaw** [comment]
Irene Changed the backgrounds to purple. It is done.
