### ISSUE TITLE
I want the cover to be clearer

### ISSUE THREAD

**Issue by BaboBrendan** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#17]
what is the change ?
Before i click start i can see the background clearer 
why do you want this change ?
Becanase before i start i will look at  the background and if i can't see i feel like this game is very bad so i will like to change the background .
How can i make the change?
i don't know

**Comment by WilliamOpenshaw** [comment]
Great, @BaboBrendan 
How can we make the background clearer?
Would you like it to be bigger?
Or would you like to change the color of the background?
Would you like to change the pentagram school image in the main menu to something else?

**Comment by CooperChenn** [comment]
The issues is solve. Now the cover is not blurry.

**Comment by CooperChenn** [comment]
I'm closing the issues for now
