### ISSUE TITLE
Add some sounds effects in the game

### ISSUE THREAD

**Issue by carlson04** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#18]
What is the change?

I want some sound effects when I click, choose options, and when I finish the game

Why do I want this change?

I think a game without sound is too boring and it'll make the whole game texture better.

How can we make this change?

I don't exactly know how to make it because it is too complicated for me.

**Comment by WilliamOpenshaw** [comment]
@carlson04 
Could you find some links to sounds you would like to use in the game?
Or could you upload them to google drive and paste the google drive link here?
If you find a sound, we can work on adding it to the game.

**Comment by CooperChenn** [comment]
We already fixed this issues
