### ISSUE TITLE
Switching between the weeks

### ISSUE THREAD

**Issue by forestlin49** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#20]
When we pick from Days X Y and Z, it immediately goes to the next slide.
I think this is a small problem because the players might not realize that they're already on a different week, which might result in clicking more than once and skipping a week.
We might be able to change this by adding a pause between the weeks, or adding effects that makes it more obvious to players that they're on another week.

**Comment by WilliamOpenshaw** [comment]
We have finished working on this issue for now. 
We added a loading screen to make sure that users can't accidentally double-click a day.
Please open up this issue again if there are still changes you feel need to made.
