### ISSUE TITLE
The result of alignment chart is hard to read.

### ISSUE THREAD

**Issue by chelseahu0129** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#22]
What is the change?
I want to change the alignment chart in to line chart or chart that can be easy to look at.
Why do you want this change?
Because chart suppose to let people to read easily but using alignment chart kind of make it hard to read.
How can we make this change?
I’m not sure how to do this. But maybe we can change in the code? 
![螢幕擷取畫面 2023-10-04 151634](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/146913950/01bcabbb-490b-476c-a4d6-02d7bf53536b)

**Comment by WilliamOpenshaw** [comment]
There are some different ways we can show the results.
Which one would be the most useful, easily readable, and satisfying for you to use?

1.
![PXL_20231006_011031767](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/660624e4-988d-403a-b6f5-28485b2f0f5e)

2.
![PXL_20231006_011109269](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/34856898-8553-41ee-8dbb-398c9dfd27a4)

3.
![PXL_20231006_011242052]
(https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/f106f820-d975-45bf-8187-53a25e52c5df)

4.
![PXL_20231006_011558080](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/5bcfea3f-53a3-49a9-a8f9-22d474f62964)

**Comment by tpreynolds19** [comment]
We could also mess around with the colors to see if a greater range of color contrasts makes things clearer?

**Comment by WilliamOpenshaw** [comment]
I have added a spider chart and a separately lined alignment chart to give more options for seeing results

radar chart
![Screenshot 2023-10-11 131611](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/6e5e5ff6-8c10-4398-811a-423ab421bd5a)

spider charts
![Screenshot 2023-10-11 131624](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/bd3425cc-6c36-4c5b-a58b-8cb6789698f0)

alignment chart
![Screenshot 2023-10-11 131636](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/c4255db0-6e5b-481a-aece-6950d3d4d2cf)

separated alignment chart
![Screenshot 2023-10-11 131650](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/aa17d0ef-4de5-4c5c-8183-0f27a144d5ec)

Does this satisfy this issue. Do we want to pick different colors.
The colors now have a black outline to make them more readable.
What other changes do we need to make.

**Comment by WilliamOpenshaw** [comment]
I will temporarily close this issue. 
Please open it back up if there are other changes that you would like to make.
