### ISSUE TITLE
To change the first slides picture to the same one as other

### ISSUE THREAD

**Issue by CooperChenn** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#24]
What is the change?
Changing the first picture of the game slides to the original one 
Why do you want this change?
I want to do this change because it can let other know better what am I doing.  
How can we make this change?
To make this change. I think we can just screenshot the picture from other and change back to the original one.

**Comment by WilliamOpenshaw** [comment]
I don't understand what you mean. 
Do you want the main menu picture to change?
Or the card colors to change?
Which picture are you talking about?

**Comment by WilliamOpenshaw** [comment]
The issue was that Cooper was using an old version of the project. After updating to the newest version, it worked.
