### ISSUE TITLE
Inability to type Chinese characters

### ISSUE THREAD

**Issue by annac1112** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#28]
The change I hope can be made is the ability to type Chinese characters with Zhuyin. As far as I can tell, right now it's not possible to do this in Unity.

The reason I've brought up this issue is that we are given the option at the start of the game to give ourselves a username or player name. The users of this ethical calculator may speak Mandarin, and may want to give themselves player names in Mandarin. It'd make for a more user-friendly experience if people could name themselves in the language of their choice.

I'm not sure how one would go about making that possible. Maybe it's not even possible. This could be a Unity issue rather than something we could just code in. I just brought this up because I think it'd be interesting if it was possible to type Chinese characters.

I don't have a picture because Unity is not letting me open the calculator.

**Comment by WilliamOpenshaw** [comment]
https://discussions.unity.com/t/how-do-i-display-chinese-in-unity/11639/2

Here's a link to some information that might help

**Comment by WilliamOpenshaw** [comment]
I'm not sure this one will be helpful, but just leaving it here.

https://forum.unity.com/threads/bugs-happen-when-typing-chinese-words-in-editor-and-ui.600541/

**Comment by WilliamOpenshaw** [comment]
![image](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/9322c374-4770-4b5a-a35d-9615d6fee522)
 
we can now display chinese

**Comment by WilliamOpenshaw** [comment]
![image](https://github.com/WilliamOpenshaw/Ethics_Calculator_Unity_Project/assets/16065395/b50d285f-382d-4019-9d17-13c6d225c7a6)

We can now type Chinese in
