### ISSUE TITLE
 The sentences were too long

### ISSUE THREAD

**Issue by Fifilai0411** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#7]
What is the change?
      I want the text to be shorter and the words can be bigger so that it will be easier to read.

why do you want this change?
      The sentences were too long and the scenarios were too crowded, so it made the player feel hard and tired to read, so it made it hard for people to understand and it would also take a long time for people to read or play the game.

How can we make this change?
      Maybe we can delete some of the content in the choices but not change the meaning of the choices so that the content won't be too crowded, also makes the players feel more comfortable while they're playing the game. in another way, we can make the box bigger, or don't show all the boxes at the same time so the screen won't be as crowded as now.

**Comment by WilliamOpenshaw** [comment]
@Fifilai0411 @Adam5111 

Both of you would like every group's text sentence choices to be shorter.
I will give you time in class to talk to the class and provide an objective for each group and an ideal sentence length.
Please talk to each other and decide together what length of sentence you would want to propose to the class, and decide together on a deadline for these changes to be made for the existing group sentence text choice strings.

**Comment by BaboBrendan** [comment]
Hi i am Brendan i will make a Announcement to everyone

**Comment by BaboBrendan** [comment]
i have done this and everyone say the size is ok

**Comment by WilliamOpenshaw** [comment]
Great, thank you for making the changes :)
@BaboBrendan
