### ISSUE TITLE
There should be space between the boxes

### ISSUE THREAD

**Issue by Adam5111** [WilliamOpenshaw/Ethics_Calculator_Unity_Project#8]
There will be bigger spaces between the choice boxes to that we can see the choices better.

I want this change because sometimes its a bit hard to see where one choice starts and one choice ends so bigger space between the choices so we can see better.

We can make the changes by shrinking the boxes a bit and simplify the sentences so that they will fit into the small box.

**Comment by WilliamOpenshaw** [comment]
Do you want to talk to each group to push for everyone to shorten their choice text sentences for their group's choices?
Please talk to me in class about completing this issue.
Also, please talk to me in class about how you would like to change the size of the cards or text boxes.
@Adam5111

**Comment by BaboBrendan** [comment]
It's fixed, adam says it is okay, space is enough.
